// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/muzyk0/online-quiz-game/internal/domain/question/models"
	"github.com/muzyk0/online-quiz-game/internal/domain/question/repository"
	"sync"
)

// Ensure, that QuestionRepositoryInterfaceMock does implement repository.QuestionRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ repository.QuestionRepositoryInterface = &QuestionRepositoryInterfaceMock{}

// QuestionRepositoryInterfaceMock is a mock implementation of repository.QuestionRepositoryInterface.
//
//	func TestSomethingThatUsesQuestionRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked repository.QuestionRepositoryInterface
//		mockedQuestionRepositoryInterface := &QuestionRepositoryInterfaceMock{
//			CreateFunc: func(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id pgtype.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*models.QuizQuestion, error) {
//				panic("mock out the GetByID method")
//			},
//			ListFunc: func(ctx context.Context, f repository.ListFilter) ([]*models.QuizQuestion, int, error) {
//				panic("mock out the List method")
//			},
//			ListPublishedFunc: func(ctx context.Context, limit int) ([]*models.QuizQuestion, error) {
//				panic("mock out the ListPublished method")
//			},
//			SetPublishedFunc: func(ctx context.Context, id pgtype.UUID, published bool) (*models.QuizQuestion, error) {
//				panic("mock out the SetPublished method")
//			},
//			UpdateFunc: func(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedQuestionRepositoryInterface in code that requires repository.QuestionRepositoryInterface
//		// and then make assertions.
//
//	}
type QuestionRepositoryInterfaceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id pgtype.UUID) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*models.QuizQuestion, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, f repository.ListFilter) ([]*models.QuizQuestion, int, error)

	// ListPublishedFunc mocks the ListPublished method.
	ListPublishedFunc func(ctx context.Context, limit int) ([]*models.QuizQuestion, error)

	// SetPublishedFunc mocks the SetPublished method.
	SetPublishedFunc func(ctx context.Context, id pgtype.UUID, published bool) (*models.QuizQuestion, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q models.QuizQuestion
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F repository.ListFilter
		}
		// ListPublished holds details about calls to the ListPublished method.
		ListPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// SetPublished holds details about calls to the SetPublished method.
		SetPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
			// Published is the published argument value.
			Published bool
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q models.QuizQuestion
		}
	}
	lockCreate        sync.RWMutex
	lockDelete        sync.RWMutex
	lockGetByID       sync.RWMutex
	lockList          sync.RWMutex
	lockListPublished sync.RWMutex
	lockSetPublished  sync.RWMutex
	lockUpdate        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *QuestionRepositoryInterfaceMock) Create(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error) {
	if mock.CreateFunc == nil {
		panic("QuestionRepositoryInterfaceMock.CreateFunc: method is nil but QuestionRepositoryInterface.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Q   models.QuizQuestion
	}{
		Ctx: ctx,
		Q:   q,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, q)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.CreateCalls())
func (mock *QuestionRepositoryInterfaceMock) CreateCalls() []struct {
	Ctx context.Context
	Q   models.QuizQuestion
} {
	var calls []struct {
		Ctx context.Context
		Q   models.QuizQuestion
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *QuestionRepositoryInterfaceMock) Delete(ctx context.Context, id pgtype.UUID) error {
	if mock.DeleteFunc == nil {
		panic("QuestionRepositoryInterfaceMock.DeleteFunc: method is nil but QuestionRepositoryInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.DeleteCalls())
func (mock *QuestionRepositoryInterfaceMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *QuestionRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*models.QuizQuestion, error) {
	if mock.GetByIDFunc == nil {
		panic("QuestionRepositoryInterfaceMock.GetByIDFunc: method is nil but QuestionRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.GetByIDCalls())
func (mock *QuestionRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *QuestionRepositoryInterfaceMock) List(ctx context.Context, f repository.ListFilter) ([]*models.QuizQuestion, int, error) {
	if mock.ListFunc == nil {
		panic("QuestionRepositoryInterfaceMock.ListFunc: method is nil but QuestionRepositoryInterface.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   repository.ListFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, f)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.ListCalls())
func (mock *QuestionRepositoryInterfaceMock) ListCalls() []struct {
	Ctx context.Context
	F   repository.ListFilter
} {
	var calls []struct {
		Ctx context.Context
		F   repository.ListFilter
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListPublished calls ListPublishedFunc.
func (mock *QuestionRepositoryInterfaceMock) ListPublished(ctx context.Context, limit int) ([]*models.QuizQuestion, error) {
	if mock.ListPublishedFunc == nil {
		panic("QuestionRepositoryInterfaceMock.ListPublishedFunc: method is nil but QuestionRepositoryInterface.ListPublished was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockListPublished.Lock()
	mock.calls.ListPublished = append(mock.calls.ListPublished, callInfo)
	mock.lockListPublished.Unlock()
	return mock.ListPublishedFunc(ctx, limit)
}

// ListPublishedCalls gets all the calls that were made to ListPublished.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.ListPublishedCalls())
func (mock *QuestionRepositoryInterfaceMock) ListPublishedCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockListPublished.RLock()
	calls = mock.calls.ListPublished
	mock.lockListPublished.RUnlock()
	return calls
}

// SetPublished calls SetPublishedFunc.
func (mock *QuestionRepositoryInterfaceMock) SetPublished(ctx context.Context, id pgtype.UUID, published bool) (*models.QuizQuestion, error) {
	if mock.SetPublishedFunc == nil {
		panic("QuestionRepositoryInterfaceMock.SetPublishedFunc: method is nil but QuestionRepositoryInterface.SetPublished was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        pgtype.UUID
		Published bool
	}{
		Ctx:       ctx,
		ID:        id,
		Published: published,
	}
	mock.lockSetPublished.Lock()
	mock.calls.SetPublished = append(mock.calls.SetPublished, callInfo)
	mock.lockSetPublished.Unlock()
	return mock.SetPublishedFunc(ctx, id, published)
}

// SetPublishedCalls gets all the calls that were made to SetPublished.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.SetPublishedCalls())
func (mock *QuestionRepositoryInterfaceMock) SetPublishedCalls() []struct {
	Ctx       context.Context
	ID        pgtype.UUID
	Published bool
} {
	var calls []struct {
		Ctx       context.Context
		ID        pgtype.UUID
		Published bool
	}
	mock.lockSetPublished.RLock()
	calls = mock.calls.SetPublished
	mock.lockSetPublished.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *QuestionRepositoryInterfaceMock) Update(ctx context.Context, q models.QuizQuestion) (*models.QuizQuestion, error) {
	if mock.UpdateFunc == nil {
		panic("QuestionRepositoryInterfaceMock.UpdateFunc: method is nil but QuestionRepositoryInterface.Update was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Q   models.QuizQuestion
	}{
		Ctx: ctx,
		Q:   q,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, q)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedQuestionRepositoryInterface.UpdateCalls())
func (mock *QuestionRepositoryInterfaceMock) UpdateCalls() []struct {
	Ctx context.Context
	Q   models.QuizQuestion
} {
	var calls []struct {
		Ctx context.Context
		Q   models.QuizQuestion
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
