// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/muzyk0/online-quiz-game/internal/domain/game/models"
	"github.com/muzyk0/online-quiz-game/internal/domain/game/repository"
	"sync"
)

// Ensure, that GameRepositoryInterfaceMock does implement repository.GameRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ repository.GameRepositoryInterface = &GameRepositoryInterfaceMock{}

// GameRepositoryInterfaceMock is a mock implementation of repository.GameRepositoryInterface.
//
//	func TestSomethingThatUsesGameRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked repository.GameRepositoryInterface
//		mockedGameRepositoryInterface := &GameRepositoryInterfaceMock{
//			ActivateGameFunc: func(ctx context.Context, gameID pgtype.UUID, secondPlayerID pgtype.UUID) (*models.QuizGame, error) {
//				panic("mock out the ActivateGame method")
//			},
//			ActivateGameWithQuestionsFunc: func(ctx context.Context, gameID pgtype.UUID, secondPlayerID pgtype.UUID, questionIDs []pgtype.UUID) (*models.QuizGame, error) {
//				panic("mock out the ActivateGameWithQuestions method")
//			},
//			AssignQuestionsFunc: func(ctx context.Context, gameID pgtype.UUID, questionIDs []pgtype.UUID) error {
//				panic("mock out the AssignQuestions method")
//			},
//			CountPlayerAnswersFunc: func(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) (int, error) {
//				panic("mock out the CountPlayerAnswers method")
//			},
//			CreatePendingFunc: func(ctx context.Context, firstPlayerID pgtype.UUID) (*models.QuizGame, error) {
//				panic("mock out the CreatePending method")
//			},
//			FindPendingFunc: func(ctx context.Context) (*models.QuizGame, error) {
//				panic("mock out the FindPending method")
//			},
//			GetActiveByPlayerIDFunc: func(ctx context.Context, playerID pgtype.UUID) (*models.QuizGame, error) {
//				panic("mock out the GetActiveByPlayerID method")
//			},
//			GetAllByPlayerIDFunc: func(ctx context.Context, playerID pgtype.UUID, filter repository.GameListFilter) ([]*models.QuizGame, int, error) {
//				panic("mock out the GetAllByPlayerID method")
//			},
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*models.QuizGame, error) {
//				panic("mock out the GetByID method")
//			},
//			GetGameQuestionsFunc: func(ctx context.Context, gameID pgtype.UUID) ([]*models.QuizGameQuestion, error) {
//				panic("mock out the GetGameQuestions method")
//			},
//			GetPlayerAnswersFunc: func(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) ([]*models.QuizGameAnswer, error) {
//				panic("mock out the GetPlayerAnswers method")
//			},
//			GetStatsByPlayerIDFunc: func(ctx context.Context, playerID pgtype.UUID) (*repository.PlayerStats, error) {
//				panic("mock out the GetStatsByPlayerID method")
//			},
//			IsPlayerInActiveGameFunc: func(ctx context.Context, playerID pgtype.UUID) (bool, error) {
//				panic("mock out the IsPlayerInActiveGame method")
//			},
//			SaveAnswerFunc: func(ctx context.Context, a models.QuizGameAnswer) (*models.QuizGameAnswer, error) {
//				panic("mock out the SaveAnswer method")
//			},
//			UpdateScoresAndFinishFunc: func(ctx context.Context, g *models.QuizGame) error {
//				panic("mock out the UpdateScoresAndFinish method")
//			},
//		}
//
//		// use mockedGameRepositoryInterface in code that requires repository.GameRepositoryInterface
//		// and then make assertions.
//
//	}
type GameRepositoryInterfaceMock struct {
	// ActivateGameFunc mocks the ActivateGame method.
	ActivateGameFunc func(ctx context.Context, gameID pgtype.UUID, secondPlayerID pgtype.UUID) (*models.QuizGame, error)

	// FindPendingAndActivateFunc mocks the FindPendingAndActivate method.
	FindPendingAndActivateFunc func(ctx context.Context, secondPlayerID pgtype.UUID, questionIDs []pgtype.UUID) (*models.QuizGame, error)

	// AssignQuestionsFunc mocks the AssignQuestions method.
	AssignQuestionsFunc func(ctx context.Context, gameID pgtype.UUID, questionIDs []pgtype.UUID) error

	// CountPlayerAnswersFunc mocks the CountPlayerAnswers method.
	CountPlayerAnswersFunc func(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) (int, error)

	// CreatePendingFunc mocks the CreatePending method.
	CreatePendingFunc func(ctx context.Context, firstPlayerID pgtype.UUID) (*models.QuizGame, error)

	// GetActiveByPlayerIDFunc mocks the GetActiveByPlayerID method.
	GetActiveByPlayerIDFunc func(ctx context.Context, playerID pgtype.UUID) (*models.QuizGame, error)

	// GetAllByPlayerIDFunc mocks the GetAllByPlayerID method.
	GetAllByPlayerIDFunc func(ctx context.Context, playerID pgtype.UUID, filter repository.GameListFilter) ([]*models.QuizGame, int, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*models.QuizGame, error)

	// GetGameQuestionsFunc mocks the GetGameQuestions method.
	GetGameQuestionsFunc func(ctx context.Context, gameID pgtype.UUID) ([]*models.QuizGameQuestion, error)

	// GetPlayerAnswersFunc mocks the GetPlayerAnswers method.
	GetPlayerAnswersFunc func(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) ([]*models.QuizGameAnswer, error)

	// GetStatsByPlayerIDFunc mocks the GetStatsByPlayerID method.
	GetStatsByPlayerIDFunc func(ctx context.Context, playerID pgtype.UUID) (*repository.PlayerStats, error)

	// IsPlayerInActiveGameFunc mocks the IsPlayerInActiveGame method.
	IsPlayerInActiveGameFunc func(ctx context.Context, playerID pgtype.UUID) (bool, error)

	// SaveAnswerFunc mocks the SaveAnswer method.
	SaveAnswerFunc func(ctx context.Context, a models.QuizGameAnswer) (*models.QuizGameAnswer, error)

	// UpdateScoresAndFinishFunc mocks the UpdateScoresAndFinish method.
	UpdateScoresAndFinishFunc func(ctx context.Context, g *models.QuizGame) error

	// calls tracks calls to the methods.
	calls struct {
		// ActivateGame holds details about calls to the ActivateGame method.
		ActivateGame []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GameID is the gameID argument value.
			GameID pgtype.UUID
			// SecondPlayerID is the secondPlayerID argument value.
			SecondPlayerID pgtype.UUID
		}
		// FindPendingAndActivate holds details about calls to the FindPendingAndActivate method.
		FindPendingAndActivate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SecondPlayerID is the secondPlayerID argument value.
			SecondPlayerID pgtype.UUID
			// QuestionIDs is the questionIDs argument value.
			QuestionIDs []pgtype.UUID
		}
		// AssignQuestions holds details about calls to the AssignQuestions method.
		AssignQuestions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GameID is the gameID argument value.
			GameID pgtype.UUID
			// QuestionIDs is the questionIDs argument value.
			QuestionIDs []pgtype.UUID
		}
		// CountPlayerAnswers holds details about calls to the CountPlayerAnswers method.
		CountPlayerAnswers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GameID is the gameID argument value.
			GameID pgtype.UUID
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
		}
		// CreatePending holds details about calls to the CreatePending method.
		CreatePending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FirstPlayerID is the firstPlayerID argument value.
			FirstPlayerID pgtype.UUID
		}
		// GetActiveByPlayerID holds details about calls to the GetActiveByPlayerID method.
		GetActiveByPlayerID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
		}
		// GetAllByPlayerID holds details about calls to the GetAllByPlayerID method.
		GetAllByPlayerID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
			// Filter is the filter argument value.
			Filter repository.GameListFilter
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetGameQuestions holds details about calls to the GetGameQuestions method.
		GetGameQuestions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GameID is the gameID argument value.
			GameID pgtype.UUID
		}
		// GetPlayerAnswers holds details about calls to the GetPlayerAnswers method.
		GetPlayerAnswers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GameID is the gameID argument value.
			GameID pgtype.UUID
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
		}
		// GetStatsByPlayerID holds details about calls to the GetStatsByPlayerID method.
		GetStatsByPlayerID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
		}
		// IsPlayerInActiveGame holds details about calls to the IsPlayerInActiveGame method.
		IsPlayerInActiveGame []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlayerID is the playerID argument value.
			PlayerID pgtype.UUID
		}
		// SaveAnswer holds details about calls to the SaveAnswer method.
		SaveAnswer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A models.QuizGameAnswer
		}
		// UpdateScoresAndFinish holds details about calls to the UpdateScoresAndFinish method.
		UpdateScoresAndFinish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// G is the g argument value.
			G *models.QuizGame
		}
	}
	lockActivateGame              sync.RWMutex
	lockFindPendingAndActivate    sync.RWMutex
	lockAssignQuestions           sync.RWMutex
	lockCountPlayerAnswers        sync.RWMutex
	lockCreatePending             sync.RWMutex
	lockGetActiveByPlayerID       sync.RWMutex
	lockGetAllByPlayerID          sync.RWMutex
	lockGetByID                   sync.RWMutex
	lockGetGameQuestions          sync.RWMutex
	lockGetPlayerAnswers          sync.RWMutex
	lockGetStatsByPlayerID        sync.RWMutex
	lockIsPlayerInActiveGame      sync.RWMutex
	lockSaveAnswer                sync.RWMutex
	lockUpdateScoresAndFinish     sync.RWMutex
}

// ActivateGame calls ActivateGameFunc.
func (mock *GameRepositoryInterfaceMock) ActivateGame(ctx context.Context, gameID pgtype.UUID, secondPlayerID pgtype.UUID) (*models.QuizGame, error) {
	if mock.ActivateGameFunc == nil {
		panic("GameRepositoryInterfaceMock.ActivateGameFunc: method is nil but GameRepositoryInterface.ActivateGame was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		GameID         pgtype.UUID
		SecondPlayerID pgtype.UUID
	}{
		Ctx:            ctx,
		GameID:         gameID,
		SecondPlayerID: secondPlayerID,
	}
	mock.lockActivateGame.Lock()
	mock.calls.ActivateGame = append(mock.calls.ActivateGame, callInfo)
	mock.lockActivateGame.Unlock()
	return mock.ActivateGameFunc(ctx, gameID, secondPlayerID)
}

// ActivateGameCalls gets all the calls that were made to ActivateGame.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.ActivateGameCalls())
func (mock *GameRepositoryInterfaceMock) ActivateGameCalls() []struct {
	Ctx            context.Context
	GameID         pgtype.UUID
	SecondPlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx            context.Context
		GameID         pgtype.UUID
		SecondPlayerID pgtype.UUID
	}
	mock.lockActivateGame.RLock()
	calls = mock.calls.ActivateGame
	mock.lockActivateGame.RUnlock()
	return calls
}

// FindPendingAndActivate calls FindPendingAndActivateFunc.
func (mock *GameRepositoryInterfaceMock) FindPendingAndActivate(ctx context.Context, secondPlayerID pgtype.UUID, questionIDs []pgtype.UUID) (*models.QuizGame, error) {
	if mock.FindPendingAndActivateFunc == nil {
		panic("GameRepositoryInterfaceMock.FindPendingAndActivateFunc: method is nil but GameRepositoryInterface.FindPendingAndActivate was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		SecondPlayerID pgtype.UUID
		QuestionIDs    []pgtype.UUID
	}{
		Ctx:            ctx,
		SecondPlayerID: secondPlayerID,
		QuestionIDs:    questionIDs,
	}
	mock.lockFindPendingAndActivate.Lock()
	mock.calls.FindPendingAndActivate = append(mock.calls.FindPendingAndActivate, callInfo)
	mock.lockFindPendingAndActivate.Unlock()
	return mock.FindPendingAndActivateFunc(ctx, secondPlayerID, questionIDs)
}

// FindPendingAndActivateCalls gets all the calls that were made to FindPendingAndActivate.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.FindPendingAndActivateCalls())
func (mock *GameRepositoryInterfaceMock) FindPendingAndActivateCalls() []struct {
	Ctx            context.Context
	SecondPlayerID pgtype.UUID
	QuestionIDs    []pgtype.UUID
} {
	var calls []struct {
		Ctx            context.Context
		SecondPlayerID pgtype.UUID
		QuestionIDs    []pgtype.UUID
	}
	mock.lockFindPendingAndActivate.RLock()
	calls = mock.calls.FindPendingAndActivate
	mock.lockFindPendingAndActivate.RUnlock()
	return calls
}

// AssignQuestions calls AssignQuestionsFunc.
func (mock *GameRepositoryInterfaceMock) AssignQuestions(ctx context.Context, gameID pgtype.UUID, questionIDs []pgtype.UUID) error {
	if mock.AssignQuestionsFunc == nil {
		panic("GameRepositoryInterfaceMock.AssignQuestionsFunc: method is nil but GameRepositoryInterface.AssignQuestions was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		GameID      pgtype.UUID
		QuestionIDs []pgtype.UUID
	}{
		Ctx:         ctx,
		GameID:      gameID,
		QuestionIDs: questionIDs,
	}
	mock.lockAssignQuestions.Lock()
	mock.calls.AssignQuestions = append(mock.calls.AssignQuestions, callInfo)
	mock.lockAssignQuestions.Unlock()
	return mock.AssignQuestionsFunc(ctx, gameID, questionIDs)
}

// AssignQuestionsCalls gets all the calls that were made to AssignQuestions.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.AssignQuestionsCalls())
func (mock *GameRepositoryInterfaceMock) AssignQuestionsCalls() []struct {
	Ctx         context.Context
	GameID      pgtype.UUID
	QuestionIDs []pgtype.UUID
} {
	var calls []struct {
		Ctx         context.Context
		GameID      pgtype.UUID
		QuestionIDs []pgtype.UUID
	}
	mock.lockAssignQuestions.RLock()
	calls = mock.calls.AssignQuestions
	mock.lockAssignQuestions.RUnlock()
	return calls
}

// CountPlayerAnswers calls CountPlayerAnswersFunc.
func (mock *GameRepositoryInterfaceMock) CountPlayerAnswers(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) (int, error) {
	if mock.CountPlayerAnswersFunc == nil {
		panic("GameRepositoryInterfaceMock.CountPlayerAnswersFunc: method is nil but GameRepositoryInterface.CountPlayerAnswers was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		GameID   pgtype.UUID
		PlayerID pgtype.UUID
	}{
		Ctx:      ctx,
		GameID:   gameID,
		PlayerID: playerID,
	}
	mock.lockCountPlayerAnswers.Lock()
	mock.calls.CountPlayerAnswers = append(mock.calls.CountPlayerAnswers, callInfo)
	mock.lockCountPlayerAnswers.Unlock()
	return mock.CountPlayerAnswersFunc(ctx, gameID, playerID)
}

// CountPlayerAnswersCalls gets all the calls that were made to CountPlayerAnswers.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.CountPlayerAnswersCalls())
func (mock *GameRepositoryInterfaceMock) CountPlayerAnswersCalls() []struct {
	Ctx      context.Context
	GameID   pgtype.UUID
	PlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		GameID   pgtype.UUID
		PlayerID pgtype.UUID
	}
	mock.lockCountPlayerAnswers.RLock()
	calls = mock.calls.CountPlayerAnswers
	mock.lockCountPlayerAnswers.RUnlock()
	return calls
}

// CreatePending calls CreatePendingFunc.
func (mock *GameRepositoryInterfaceMock) CreatePending(ctx context.Context, firstPlayerID pgtype.UUID) (*models.QuizGame, error) {
	if mock.CreatePendingFunc == nil {
		panic("GameRepositoryInterfaceMock.CreatePendingFunc: method is nil but GameRepositoryInterface.CreatePending was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		FirstPlayerID pgtype.UUID
	}{
		Ctx:           ctx,
		FirstPlayerID: firstPlayerID,
	}
	mock.lockCreatePending.Lock()
	mock.calls.CreatePending = append(mock.calls.CreatePending, callInfo)
	mock.lockCreatePending.Unlock()
	return mock.CreatePendingFunc(ctx, firstPlayerID)
}

// CreatePendingCalls gets all the calls that were made to CreatePending.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.CreatePendingCalls())
func (mock *GameRepositoryInterfaceMock) CreatePendingCalls() []struct {
	Ctx           context.Context
	FirstPlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx           context.Context
		FirstPlayerID pgtype.UUID
	}
	mock.lockCreatePending.RLock()
	calls = mock.calls.CreatePending
	mock.lockCreatePending.RUnlock()
	return calls
}

// FindPending calls FindPendingFunc.
// GetActiveByPlayerID calls GetActiveByPlayerIDFunc.
func (mock *GameRepositoryInterfaceMock) GetActiveByPlayerID(ctx context.Context, playerID pgtype.UUID) (*models.QuizGame, error) {
	if mock.GetActiveByPlayerIDFunc == nil {
		panic("GameRepositoryInterfaceMock.GetActiveByPlayerIDFunc: method is nil but GameRepositoryInterface.GetActiveByPlayerID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}{
		Ctx:      ctx,
		PlayerID: playerID,
	}
	mock.lockGetActiveByPlayerID.Lock()
	mock.calls.GetActiveByPlayerID = append(mock.calls.GetActiveByPlayerID, callInfo)
	mock.lockGetActiveByPlayerID.Unlock()
	return mock.GetActiveByPlayerIDFunc(ctx, playerID)
}

// GetActiveByPlayerIDCalls gets all the calls that were made to GetActiveByPlayerID.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetActiveByPlayerIDCalls())
func (mock *GameRepositoryInterfaceMock) GetActiveByPlayerIDCalls() []struct {
	Ctx      context.Context
	PlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}
	mock.lockGetActiveByPlayerID.RLock()
	calls = mock.calls.GetActiveByPlayerID
	mock.lockGetActiveByPlayerID.RUnlock()
	return calls
}

// GetAllByPlayerID calls GetAllByPlayerIDFunc.
func (mock *GameRepositoryInterfaceMock) GetAllByPlayerID(ctx context.Context, playerID pgtype.UUID, filter repository.GameListFilter) ([]*models.QuizGame, int, error) {
	if mock.GetAllByPlayerIDFunc == nil {
		panic("GameRepositoryInterfaceMock.GetAllByPlayerIDFunc: method is nil but GameRepositoryInterface.GetAllByPlayerID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
		Filter   repository.GameListFilter
	}{
		Ctx:      ctx,
		PlayerID: playerID,
		Filter:   filter,
	}
	mock.lockGetAllByPlayerID.Lock()
	mock.calls.GetAllByPlayerID = append(mock.calls.GetAllByPlayerID, callInfo)
	mock.lockGetAllByPlayerID.Unlock()
	return mock.GetAllByPlayerIDFunc(ctx, playerID, filter)
}

// GetAllByPlayerIDCalls gets all the calls that were made to GetAllByPlayerID.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetAllByPlayerIDCalls())
func (mock *GameRepositoryInterfaceMock) GetAllByPlayerIDCalls() []struct {
	Ctx      context.Context
	PlayerID pgtype.UUID
	Filter   repository.GameListFilter
} {
	var calls []struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
		Filter   repository.GameListFilter
	}
	mock.lockGetAllByPlayerID.RLock()
	calls = mock.calls.GetAllByPlayerID
	mock.lockGetAllByPlayerID.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *GameRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*models.QuizGame, error) {
	if mock.GetByIDFunc == nil {
		panic("GameRepositoryInterfaceMock.GetByIDFunc: method is nil but GameRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetByIDCalls())
func (mock *GameRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetGameQuestions calls GetGameQuestionsFunc.
func (mock *GameRepositoryInterfaceMock) GetGameQuestions(ctx context.Context, gameID pgtype.UUID) ([]*models.QuizGameQuestion, error) {
	if mock.GetGameQuestionsFunc == nil {
		panic("GameRepositoryInterfaceMock.GetGameQuestionsFunc: method is nil but GameRepositoryInterface.GetGameQuestions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		GameID pgtype.UUID
	}{
		Ctx:    ctx,
		GameID: gameID,
	}
	mock.lockGetGameQuestions.Lock()
	mock.calls.GetGameQuestions = append(mock.calls.GetGameQuestions, callInfo)
	mock.lockGetGameQuestions.Unlock()
	return mock.GetGameQuestionsFunc(ctx, gameID)
}

// GetGameQuestionsCalls gets all the calls that were made to GetGameQuestions.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetGameQuestionsCalls())
func (mock *GameRepositoryInterfaceMock) GetGameQuestionsCalls() []struct {
	Ctx    context.Context
	GameID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		GameID pgtype.UUID
	}
	mock.lockGetGameQuestions.RLock()
	calls = mock.calls.GetGameQuestions
	mock.lockGetGameQuestions.RUnlock()
	return calls
}

// GetPlayerAnswers calls GetPlayerAnswersFunc.
func (mock *GameRepositoryInterfaceMock) GetPlayerAnswers(ctx context.Context, gameID pgtype.UUID, playerID pgtype.UUID) ([]*models.QuizGameAnswer, error) {
	if mock.GetPlayerAnswersFunc == nil {
		panic("GameRepositoryInterfaceMock.GetPlayerAnswersFunc: method is nil but GameRepositoryInterface.GetPlayerAnswers was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		GameID   pgtype.UUID
		PlayerID pgtype.UUID
	}{
		Ctx:      ctx,
		GameID:   gameID,
		PlayerID: playerID,
	}
	mock.lockGetPlayerAnswers.Lock()
	mock.calls.GetPlayerAnswers = append(mock.calls.GetPlayerAnswers, callInfo)
	mock.lockGetPlayerAnswers.Unlock()
	return mock.GetPlayerAnswersFunc(ctx, gameID, playerID)
}

// GetPlayerAnswersCalls gets all the calls that were made to GetPlayerAnswers.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetPlayerAnswersCalls())
func (mock *GameRepositoryInterfaceMock) GetPlayerAnswersCalls() []struct {
	Ctx      context.Context
	GameID   pgtype.UUID
	PlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		GameID   pgtype.UUID
		PlayerID pgtype.UUID
	}
	mock.lockGetPlayerAnswers.RLock()
	calls = mock.calls.GetPlayerAnswers
	mock.lockGetPlayerAnswers.RUnlock()
	return calls
}

// GetStatsByPlayerID calls GetStatsByPlayerIDFunc.
func (mock *GameRepositoryInterfaceMock) GetStatsByPlayerID(ctx context.Context, playerID pgtype.UUID) (*repository.PlayerStats, error) {
	if mock.GetStatsByPlayerIDFunc == nil {
		panic("GameRepositoryInterfaceMock.GetStatsByPlayerIDFunc: method is nil but GameRepositoryInterface.GetStatsByPlayerID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}{
		Ctx:      ctx,
		PlayerID: playerID,
	}
	mock.lockGetStatsByPlayerID.Lock()
	mock.calls.GetStatsByPlayerID = append(mock.calls.GetStatsByPlayerID, callInfo)
	mock.lockGetStatsByPlayerID.Unlock()
	return mock.GetStatsByPlayerIDFunc(ctx, playerID)
}

// GetStatsByPlayerIDCalls gets all the calls that were made to GetStatsByPlayerID.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.GetStatsByPlayerIDCalls())
func (mock *GameRepositoryInterfaceMock) GetStatsByPlayerIDCalls() []struct {
	Ctx      context.Context
	PlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}
	mock.lockGetStatsByPlayerID.RLock()
	calls = mock.calls.GetStatsByPlayerID
	mock.lockGetStatsByPlayerID.RUnlock()
	return calls
}

// IsPlayerInActiveGame calls IsPlayerInActiveGameFunc.
func (mock *GameRepositoryInterfaceMock) IsPlayerInActiveGame(ctx context.Context, playerID pgtype.UUID) (bool, error) {
	if mock.IsPlayerInActiveGameFunc == nil {
		panic("GameRepositoryInterfaceMock.IsPlayerInActiveGameFunc: method is nil but GameRepositoryInterface.IsPlayerInActiveGame was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}{
		Ctx:      ctx,
		PlayerID: playerID,
	}
	mock.lockIsPlayerInActiveGame.Lock()
	mock.calls.IsPlayerInActiveGame = append(mock.calls.IsPlayerInActiveGame, callInfo)
	mock.lockIsPlayerInActiveGame.Unlock()
	return mock.IsPlayerInActiveGameFunc(ctx, playerID)
}

// IsPlayerInActiveGameCalls gets all the calls that were made to IsPlayerInActiveGame.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.IsPlayerInActiveGameCalls())
func (mock *GameRepositoryInterfaceMock) IsPlayerInActiveGameCalls() []struct {
	Ctx      context.Context
	PlayerID pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		PlayerID pgtype.UUID
	}
	mock.lockIsPlayerInActiveGame.RLock()
	calls = mock.calls.IsPlayerInActiveGame
	mock.lockIsPlayerInActiveGame.RUnlock()
	return calls
}

// SaveAnswer calls SaveAnswerFunc.
func (mock *GameRepositoryInterfaceMock) SaveAnswer(ctx context.Context, a models.QuizGameAnswer) (*models.QuizGameAnswer, error) {
	if mock.SaveAnswerFunc == nil {
		panic("GameRepositoryInterfaceMock.SaveAnswerFunc: method is nil but GameRepositoryInterface.SaveAnswer was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   models.QuizGameAnswer
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockSaveAnswer.Lock()
	mock.calls.SaveAnswer = append(mock.calls.SaveAnswer, callInfo)
	mock.lockSaveAnswer.Unlock()
	return mock.SaveAnswerFunc(ctx, a)
}

// SaveAnswerCalls gets all the calls that were made to SaveAnswer.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.SaveAnswerCalls())
func (mock *GameRepositoryInterfaceMock) SaveAnswerCalls() []struct {
	Ctx context.Context
	A   models.QuizGameAnswer
} {
	var calls []struct {
		Ctx context.Context
		A   models.QuizGameAnswer
	}
	mock.lockSaveAnswer.RLock()
	calls = mock.calls.SaveAnswer
	mock.lockSaveAnswer.RUnlock()
	return calls
}

// UpdateScoresAndFinish calls UpdateScoresAndFinishFunc.
func (mock *GameRepositoryInterfaceMock) UpdateScoresAndFinish(ctx context.Context, g *models.QuizGame) error {
	if mock.UpdateScoresAndFinishFunc == nil {
		panic("GameRepositoryInterfaceMock.UpdateScoresAndFinishFunc: method is nil but GameRepositoryInterface.UpdateScoresAndFinish was just called")
	}
	callInfo := struct {
		Ctx context.Context
		G   *models.QuizGame
	}{
		Ctx: ctx,
		G:   g,
	}
	mock.lockUpdateScoresAndFinish.Lock()
	mock.calls.UpdateScoresAndFinish = append(mock.calls.UpdateScoresAndFinish, callInfo)
	mock.lockUpdateScoresAndFinish.Unlock()
	return mock.UpdateScoresAndFinishFunc(ctx, g)
}

// UpdateScoresAndFinishCalls gets all the calls that were made to UpdateScoresAndFinish.
// Check the length with:
//
//	len(mockedGameRepositoryInterface.UpdateScoresAndFinishCalls())
func (mock *GameRepositoryInterfaceMock) UpdateScoresAndFinishCalls() []struct {
	Ctx context.Context
	G   *models.QuizGame
} {
	var calls []struct {
		Ctx context.Context
		G   *models.QuizGame
	}
	mock.lockUpdateScoresAndFinish.RLock()
	calls = mock.calls.UpdateScoresAndFinish
	mock.lockUpdateScoresAndFinish.RUnlock()
	return calls
}
