// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/muzyk0/online-quiz-game/internal/domain/user/models"
	"github.com/muzyk0/online-quiz-game/internal/domain/user/repository"
	"sync"
)

// Ensure, that UserRepositoryInterfaceMock does implement repository.UserRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ repository.UserRepositoryInterface = &UserRepositoryInterfaceMock{}

// UserRepositoryInterfaceMock is a mock implementation of repository.UserRepositoryInterface.
//
//	func TestSomethingThatUsesUserRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked repository.UserRepositoryInterface
//		mockedUserRepositoryInterface := &UserRepositoryInterfaceMock{
//			CreateFunc: func(ctx context.Context, user models.User) (*models.User, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id pgtype.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*models.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*models.User, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByLoginFunc: func(ctx context.Context, login string) (*models.User, error) {
//				panic("mock out the GetByLogin method")
//			},
//			ListSAFunc: func(ctx context.Context, f repository.SAListFilter) ([]*models.User, int, error) {
//				panic("mock out the ListSA method")
//			},
//			UpdateFunc: func(ctx context.Context, user models.User) (*models.User, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepositoryInterface in code that requires repository.UserRepositoryInterface
//		// and then make assertions.
//
//	}
type UserRepositoryInterfaceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user models.User) (*models.User, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id pgtype.UUID) error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*models.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*models.User, error)

	// GetByLoginFunc mocks the GetByLogin method.
	GetByLoginFunc func(ctx context.Context, login string) (*models.User, error)

	// ListSAFunc mocks the ListSA method.
	ListSAFunc func(ctx context.Context, f repository.SAListFilter) ([]*models.User, int, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user models.User) (*models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User models.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetByLogin holds details about calls to the GetByLogin method.
		GetByLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Login is the login argument value.
			Login string
		}
		// ListSA holds details about calls to the ListSA method.
		ListSA []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F repository.SAListFilter
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User models.User
		}
	}
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockGetByEmail sync.RWMutex
	lockGetByID    sync.RWMutex
	lockGetByLogin sync.RWMutex
	lockListSA     sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepositoryInterfaceMock) Create(ctx context.Context, user models.User) (*models.User, error) {
	if mock.CreateFunc == nil {
		panic("UserRepositoryInterfaceMock.CreateFunc: method is nil but UserRepositoryInterface.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User models.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.CreateCalls())
func (mock *UserRepositoryInterfaceMock) CreateCalls() []struct {
	Ctx  context.Context
	User models.User
} {
	var calls []struct {
		Ctx  context.Context
		User models.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryInterfaceMock) Delete(ctx context.Context, id pgtype.UUID) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryInterfaceMock.DeleteFunc: method is nil but UserRepositoryInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.DeleteCalls())
func (mock *UserRepositoryInterfaceMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepositoryInterfaceMock) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepositoryInterfaceMock.GetByEmailFunc: method is nil but UserRepositoryInterface.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.GetByEmailCalls())
func (mock *UserRepositoryInterfaceMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*models.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserRepositoryInterfaceMock.GetByIDFunc: method is nil but UserRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.GetByIDCalls())
func (mock *UserRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByLogin calls GetByLoginFunc.
func (mock *UserRepositoryInterfaceMock) GetByLogin(ctx context.Context, login string) (*models.User, error) {
	if mock.GetByLoginFunc == nil {
		panic("UserRepositoryInterfaceMock.GetByLoginFunc: method is nil but UserRepositoryInterface.GetByLogin was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Login string
	}{
		Ctx:   ctx,
		Login: login,
	}
	mock.lockGetByLogin.Lock()
	mock.calls.GetByLogin = append(mock.calls.GetByLogin, callInfo)
	mock.lockGetByLogin.Unlock()
	return mock.GetByLoginFunc(ctx, login)
}

// GetByLoginCalls gets all the calls that were made to GetByLogin.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.GetByLoginCalls())
func (mock *UserRepositoryInterfaceMock) GetByLoginCalls() []struct {
	Ctx   context.Context
	Login string
} {
	var calls []struct {
		Ctx   context.Context
		Login string
	}
	mock.lockGetByLogin.RLock()
	calls = mock.calls.GetByLogin
	mock.lockGetByLogin.RUnlock()
	return calls
}

// ListSA calls ListSAFunc.
func (mock *UserRepositoryInterfaceMock) ListSA(ctx context.Context, f repository.SAListFilter) ([]*models.User, int, error) {
	if mock.ListSAFunc == nil {
		panic("UserRepositoryInterfaceMock.ListSAFunc: method is nil but UserRepositoryInterface.ListSA was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   repository.SAListFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListSA.Lock()
	mock.calls.ListSA = append(mock.calls.ListSA, callInfo)
	mock.lockListSA.Unlock()
	return mock.ListSAFunc(ctx, f)
}

// ListSACalls gets all the calls that were made to ListSA.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.ListSACalls())
func (mock *UserRepositoryInterfaceMock) ListSACalls() []struct {
	Ctx context.Context
	F   repository.SAListFilter
} {
	var calls []struct {
		Ctx context.Context
		F   repository.SAListFilter
	}
	mock.lockListSA.RLock()
	calls = mock.calls.ListSA
	mock.lockListSA.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryInterfaceMock) Update(ctx context.Context, user models.User) (*models.User, error) {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryInterfaceMock.UpdateFunc: method is nil but UserRepositoryInterface.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User models.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.UpdateCalls())
func (mock *UserRepositoryInterfaceMock) UpdateCalls() []struct {
	Ctx  context.Context
	User models.User
} {
	var calls []struct {
		Ctx  context.Context
		User models.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
